version: '3.3'
services:
  telegram_bot:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    command: python launch_telegram.py
    env_file:
      - .env
  db:
    container_name: db
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./resources/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_BASENAME}"
