"""Add db_name, age to user

Revision ID: 4ed77e70e677
Revises: 71b42c63f156
Create Date: 2024-08-02 20:04:38.361677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed77e70e677'
down_revision: Union[str, None] = '71b42c63f156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('db_name', sa.String(), nullable=True))
    op.add_column('telegram_users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'age')
    op.drop_column('telegram_users', 'db_name')
    # ### end Alembic commands ###
